DROP TABLE T_ITEM_COMMENT;
DROP TABLE T_CURRENCY;
DROP TABLE T_ITEM_META;
DROP TABLE T_ITEM;
DROP TABLE T_ITEM_STATS;
DROP TABLE T_META_FIELDS;
DROP TABLE T_ITEM_RESOURCE;
DROP TABLE T_KEYWORDS;
DROP TABLE T_CATEGORY;
DROP TABLE T_PLUGIN_CATEGORY;
DROP TABLE T_CATEGORY_STATS;
DROP TABLE T_CITY;
DROP TABLE T_CITY_AREA;
DROP TABLE T_ITEM_LOCATION;
DROP TABLE T_META_CATEGORIES;
DROP TABLE T_META_FIELDS;
DROP TABLE T_META_CATEGORIES;
DROP TABLE T_CATEGORY;
DROP TABLE T_CATEGORY_DESCRIPTION;
DROP TABLE T_KEYWORDS;
DROP TABLE T_CATEGORY_STATS;
DROP TABLE T_PLUGIN_CATEGORY;
DROP TABLE T_COUNTRY;
DROP TABLE T_REGION;
DROP TABLE T_CITY;
DROP TABLE T_CITY_AREA;
DROP TABLE T_ITEM_LOCATION;
DROP TABLE T_LOCALE;
DROP TABLE T_USER;
DROP TABLE T_USER_EMAIL_TMP;
DROP TABLE T_PAGES;
DROP TABLE T_PAGES_DESCRIPTION;
DROP TABLE T_WIDGET;
DROP TABLE T_ALERTS;
DROP TABLE T_ADMIN;
DROP TABLE T_PREFERENCE;
DROP TABLE T_LOG;
DROP TABLE T_LATEST_SEARCHES;
DROP TABLE T_CRON;
DROP TABLE ITEM_DESCRIPTION;
--

-------------------------------------||
-------ITEM SECTION------------------||
-------------------------------------||



CREATE TABLE T_ITEM(
PK_I_ID NUMBER(10,0) PRIMARY KEY,
FK_I_USER_ID NUMBER(10,0),
FK_I_CATEGORY_ID NUMBER(10,0),
DT_PUB_DATE TIMESTAMP,
DT_MOD_DATE TIMESTAMP,
F_PRICE NUMBER(10,2),
I_PRICE NUMBER(10,2),
FK_C_CURRENCY_CODE CHAR(3),
S_CONTACT_NAME VARCHAR2(100),
S_CONTACT_EMAIL VARCHAR2(140),
B_PREMIUM NUMBER(1,0),
B_ENABLED NUMBER(1,0),
B_ACTIVE NUMBER(1,0),
B_SPAM NUMBER(1,0),
S_SECRET VARCHAR2(40),
B_SHOW_EMAIL NUMBER(1,0));

CREATE TABLE ITEM_DESCRIPTION(
FK_I_ITEM_ID NUMBER(10,0),
FK_C_LOCALE_CODE CHAR(5),
S_TITLE VARCHAR(100),
S_DESCRIPTION VARCHAR2(512));



CREATE TABLE T_ITEM_COMMENT(
PK_I_ID NUMBER(10,0) PRIMARY KEY,
FK_I_ITEM_ID NUMBER(10,0),
DT_PUB_DATE TIMESTAMP ,
S_TITLE VARCHAR2(200),
S_AUTHOR_NAME VARCHAR2(100),
S_AUTHOR_EMAIL VARCHAR2(100),
S_BODY VARCHAR2(512),
B_ENABLED NUMBER(1,0),
B_ACTIVE NUMBER(1,0),
B_SPAM NUMBER(1,0),
FK_I_USER_ID NUMBER(10,0));





CREATE TABLE T_ITEM_STATS(
FK_I_ITEM_ID NUMBER(10,0) PRIMARY KEY,
I_NUM_VIEWS NUMBER(10,0),
I_NUM_SPAM NUMBER(10,0),
I_NUM_REPEATED NUMBER(10,0),
I_NUM_BAD_CLASSIFIED NUMBER(10,0),
I_NUM_OFFENSIVE NUMBER(10,0),
I_NUM_EXPIRED NUMBER(10,0),
I_NUM_PREMIUM_VIEWS NUMBER(10,0),
DT_DATE TIMESTAMP);



CREATE TABLE T_ITEM_RESOURCE(
PK_I_ID NUMBER(10,0) PRIMARY KEY,
FK_I_ITEM_ID NUMBER(10,0),
S_NAME VARCHAR2(60),
S_EXTENSION VARCHAR2(40),
S_CONTENT_TYPE VARCHAR2(40),
S_PATH VARCHAR2(250));


CREATE TABLE T_CURRENCY(
PK_C_CODE CHAR(3) PRIMARY KEY,
S_NAME VARCHAR2(40),
S_DESCRIPTION VARCHAR2(80),
B_ENABLED NUMBER(1,0)
);


-------------------------------------||
-------META SECTION------------------||
-------------------------------------||

CREATE TABLE T_ITEM_META(
FK_I_ITEM_ID NUMBER(10,0),
FK_I_FIELD_ID NUMBER(10,0),
S_VALUE VARCHAR2(512)
);


CREATE TABLE T_META_FIELDS(
PK_I_ID NUMBER(10,0) PRIMARY KEY,
S_NAME VARCHAR2(255),
S_SLUG VARCHAR2(255),
E_TYPE NUMBER,
S_OPTIONS VARCHAR2(255),
B_REQUIRED NUMBER(1,0)
);


CREATE TABLE T_META_CATEGORIES(
FK_I_CATEGORY_ID NUMBER(10,0) PRIMARY KEY,
FK_I_FIELD_ID NUMBER(10,0));


-------------------------------------||
-------CATEGORY SECTION--------------||
-------------------------------------||



CREATE TABLE T_CATEGORY(
PK_I_ID NUMBER(10,0) PRIMARY KEY,
FK_I_PARENT_ID NUMBER(10,0),
I_EXPIRATION_DAYS NUMBER(3,0),
I_POSITION NUMBER(2,0),
B_ENABLED NUMBER(1,0),
S_ICON VARCHAR2(250));


CREATE TABLE T_CATEGORY_DESCRIPTION(
FK_I_CATEGORY_ID NUMBER(10,0),
FK_C_LOCALE_CODE CHAR(5),
S_NAME VARCHAR2(100),
S_DESCRIPTION VARCHAR2(512),
S_SLUG VARCHAR2(100));


CREATE TABLE T_KEYWORDS(
S_MD5 VARCHAR2(32) PRIMARY KEY,
FK_C_LOCALE_CODE CHAR(5),
S_ORIGINAL_TEXT VARCHAR2(255),
S_ANCHOR_TEXT VARCHAR2(255),
S_NORMALIZED_TEXT VARCHAR2(255),
FK_I_CATEGORY_ID NUMBER(10,0),
FK_I_CITY_ID NUMBER(10,0));



CREATE TABLE T_CATEGORY_STATS(
FK_I_CATEGORY_ID NUMBER(10,0) PRIMARY KEY,
I_NUM_ITEMS NUMBER(10,0)
);


CREATE TABLE T_PLUGIN_CATEGORY(
S_PLUGIN_NAME VARCHAR2(40),
FK_I_CATEGORY_ID NUMBER(10,0));



-------------------------------------||
-------LOCATION SECTION--------------||
-------------------------------------||

CREATE TABLE T_COUNTRY(
PK_C_CODE CHAR(2) PRIMARY KEY, 
FK_C_LOCALE_CODE CHAR(5),
S_NAME VARCHAR2(80));

CREATE TABLE T_REGION(
PK_I_ID NUMBER(10,0),
FK_C_COUNTRY_CODE CHAR(2),
S_NAME VARCHAR2(60),
B_ACTIVE NUMBER(1,0));


CREATE TABLE T_CITY(
PK_I_ID NUMBER(10,0) PRIMARY KEY,
FK_I_REGION_ID NUMBER(10,0),
S_NAME VARCHAR2(60),
FK_C_COUNTRY_CODE CHAR(2),
B_ACTIVE NUMBER(1,0));

CREATE TABLE T_CITY_AREA(
PK_I_ID NUMBER(10,0),
FK_I_CITY_IID  NUMBER(10,0),
S_NAME VARCHAR2(255));

CREATE TABLE T_ITEM_LOCATION(
FK_I_ITEM_ID NUMBER(10,0) PRIMARY KEY,
FK_C_COUNTRY_CODE CHAR(2),
S_COUNTRY VARCHAR2(40),
S_ADDRESS VARCHAR2(100),
S_ZIP VARCHAR2(15),
FK_I_REGION_ID NUMBER(10,0),
S_REGION VARCHAR2(100),
FK_I_CITY_ID NUMBER(10,0),
S_CITY VARCHAR2(100),
FK_I_CITY_AREA_ID NUMBER(10,0),
S_CITY_AREA VARCHAR2(200),
D_COORD_LAT NUMBER(10,5),
D_COORD_LONG NUMBER(10,5));


CREATE TABLE T_LOCALE(
PK_C_CODE CHAR(5),
S_NAME VARCHAR2(100),
S_SHORT_NAME VARCHAR2(40),
S_DESCRIPTION VARCHAR2(100),
S_VERSION VARCHAR2(100),
S_AUTHOR_NAME VARCHAR2(100),
S_AUTHOR_URL VARCHAR(100),
S_CURRENCY_FORMAT VARCHAR2(50),
S_DEC_POINT VARCHAR2(2),
S_THOUSANDS_SEP VARCHAR2(2),
I_NUM_DEC NUMBER(4,0),
S_DATE_FORMAT VARCHAR2(20),
S_STOP_WORDS VARCHAR2(512),
B_ENABLED NUMBER(1,0),
B_ENABLED_BO NUMBER(1,0));



-------------------------------------||
-------USER SECTION------------------||
-------------------------------------||


CREATE TABLE T_USER(
PK_I_ID NUMBER(10,0),
DT_REG_DATE TIMESTAMP,
DT_MOD_DATE TIMESTAMP,
S_NAME VARCHAR2(100),
S_PASSWORD VARCHAR2(40),
S_SECRET VARCHAR2(40),
S_EMAIL VARCHAR2(100),
S_WEBSITE VARCHAR2(100),
S_PHONE_LAND VARCHAR2(45),
S_PHONE_MOBILE VARCHAR2(45),
B_ENABLED NUMBER(1,0),
B_ACTIVE NUMBER(1,0),
S_PASS_CODE VARCHAR2(100),
S_PASS_QUESTION VARCHAR2(100),
S_PASS_ANSWER VARCHAR2(100),
S_PASS_IP VARCHAR2(15),
FK_C_COUNTRY_CODE CHAR(2),
S_COUNTRY VARCHAR2(40),
S_ADDRESS VARCHAR2(100),
S_ZIP VARCHAR2(15),
FK_I_REGION_ID NUMBER(10,0),
S_REGION VARCHAR2(100),
FK_I_CITY_ID NUMBER(10,0),
S_CITY VARCHAR2(100),
FK_I_CITY_AREA_ID NUMBER(10,0),
S_CITY_AREA VARCHAR2(100),
D_COORD_LAT NUMBER(10,5),
D_COORD_LONG NUMBER(10,5),
I_PERMISSIONS VARCHAR(2));


CREATE TABLE T_USER_EMAIL_TMP(
FK_I_USER_ID NUMBER(10,0),
S_NEW_EMAIL VARCHAR2(100),
DT_DATE TIMESTAMP);



-------------------------------------||
-------WEBSITE SECTION---------------||
-------------------------------------||

CREATE TABLE T_PAGES(
PK_I_ID NUMBER(10,0),
S_INTERNAL_NAME VARCHAR2(50),
B_INDELIBLE NUMBER(1,0),
DT_PUB_DATE TIMESTAMP,
DT_MOD_DATE TIMESTAMP,
I_ORDER NUMBER(3));


CREATE TABLE T_PAGES_DESCRIPTION(
FK_I_PAGES_ID NUMBER(10,0),
FK_C_LOCALE_CODE CHAR(5),
S_TITLE VARCHAR(255),
S_TEXT VARCHAR2(512));


CREATE TABLE T_WIDGET(
PK_I_ID NUMBER(10,0) PRIMARY KEY,
S_DESCRIPTION VARCHAR2(40),
S_LOCATION VARCHAR2(40),
E_KIND CHAR(4) CHECK( E_KIND IN('TEXT','HTML')),
S_CONTENT VARCHAR2(512));

CREATE TABLE T_ALERTS(
S_EMAIL VARCHAR(100),
FK_I_USER_ID NUMBER(10,0),
S_SEARCH VARCHAR2(512),
S_SECRET VARCHAR2(40),
B_ACTIVE NUMBER(1,0),
E_TYPE NUMBER(10));


CREATE TABLE T_ADMIN(
PK_I_ID NUMBER(10,0) PRIMARY KEY,
S_NAME VARCHAR2(100),
S_USERNAME VARCHAR2(40),
S_PASSWORD VARCHAR2(40),
S_EMAIL VARCHAR2(100),
S_SECRET VARCHAR2(40));


CREATE TABLE T_PREFERENCE(
S_SECTION VARCHAR2(40),
S_NAME VARCHAR2(40),
S_VALUE VARCHAR2(512),
E_TYPE NUMBER(10));


CREATE TABLE T_LOG(
DT_DATE TIMESTAMP,
S_SECTION VARCHAR2(50),
S_ACTION VARCHAR2(50),
FK_I_ID NUMBER(10,0),
S_DATA VARCHAR2(250),
S_IP VARCHAR2(50),
S_WHO VARCHAR2(50),
FK_I_WHO_ID NUMBER(10,0));


CREATE TABLE T_LATEST_SEARCHES(
D_DATE TIMESTAMP,
S_SEARCH VARCHAR2(255));


CREATE TABLE T_CRON(
E_TYPE NUMBER(10),
D_LAST_EXEC TIMESTAMP,
D_NEXT_EXEC TIMESTAMP);





-------------------------------------||
-------CONSTRAINTS-------------------||
-------------------------------------||

------FOREIGN KEYS


--ITEM ID
ALTER TABLE T_ITEM_COMMENT ADD CONSTRAINT FK_T_ITEM_COMMENT_ITEM_ID FOREIGN KEY(FK_I_ITEM_ID) REFERENCES T_ITEM(PK_I_ID);
ALTER TABLE ITEM_DESCRIPTION ADD CONSTRAINT FK_T_ITEM_DESCRIPTION_ITEM_ID FOREIGN KEY(FK_I_ITEM_ID) REFERENCES T_ITEM(PK_I_ID);
ALTER TABLE T_ITEM_STATS ADD CONSTRAINT FK_T_ITEM_STATS_ITEM_ID FOREIGN KEY(FK_I_ITEM_ID) REFERENCES T_ITEM(PK_I_ID);
ALTER TABLE T_ITEM_RESOURCE ADD CONSTRAINT FK_T_ITEM_RESOURCE_ITEM_ID FOREIGN KEY(FK_I_ITEM_ID) REFERENCES T_ITEM(PK_I_ID);
ALTER TABLE T_ITEM_META ADD CONSTRAINT FK_T_ITEM_META_ITEM_ID FOREIGN KEY(FK_I_ITEM_ID) REFERENCES T_ITEM(PK_I_ID);
ALTER TABLE T_ITEM_LOCATION ADD CONSTRAINT FK_T_ITEM_LOCATION_ITEM_ID FOREIGN KEY(FK_I_ITEM_ID) REFERENCES T_ITEM(PK_I_ID);




















